title: Harvard Nano-Design Research Group
collections:
  people:
    output: true
    permalink: /people/:path/
  projects:
    output: true
    permalink: /research/:path/
sass:
  sass_dir: _sass
  style: compressed # Optional: results in a smaller CSS file